- hosts: all
  become: true
  tasks:
    - name: Restart service SPLUNK in all cases
      service:
        name: splunk
        state: started
    - name: Waits for port 8000 of any IP to close active connections, don't start checking for 10 seconds
      wait_for:
         host: 0.0.0.0
         port: 8000
         delay: 10
